/**
 * Dashboard Logic
 * Handles payment flow and number selection for regular users
 */

let currentUser = null;
let paymentStatus = null;
let numberMatrix = null;
let refreshInterval = null;
let currentScores = [];
let autoGeneratedNumbers = [];

document.addEventListener('DOMContentLoaded', async () => {
  await init();

  document.getElementById('logoutBtn').addEventListener('click', handleLogout);
  document.getElementById('joinBolaoBtn').addEventListener('click', handleJoinBolao);
  document.getElementById('alreadyPaidBtn').addEventListener('click', handleAlreadyPaid);

  // 👉 BOTÃO COPIAR PIX
  const copyBtn = document.getElementById('copyPixBtn');
  const pixKeyEl = document.getElementById('pixKeyValue');

  if (copyBtn && pixKeyEl) {
    copyBtn.addEventListener('click', async () => {
      try {
        await navigator.clipboard.writeText(pixKeyEl.textContent.trim());
        showToast('✅ Chave PIX copiada!', 'success');
      } catch (err) {
        console.error(err);
        showToast('❌ Erro ao copiar a chave PIX', 'error');
      }
    });
  }

  const quotaInput = document.getElementById('quotaQuantity');
  if (quotaInput) quotaInput.addEventListener('input', updateTotalAmount);

  refreshInterval = setInterval(refreshData, 30000);
});

/* ================= INIT ================= */

async function init() {
  try {
    showLoading(true);
    currentUser = await checkAuth();

    if (!currentUser) {
      window.location.href = '/';
      return;
    }

    document.getElementById('userName').textContent = `Olá, ${currentUser.name}!`;

    if (currentUser.isAdmin) {
      const adminBtn = document.getElementById('adminPanelBtn');
      if (adminBtn) adminBtn.style.display = 'inline-block';
    }

    await loadPaymentStatus();
    await loadBolaoInfo();

  } catch (err) {
    console.error(err);
    showToast('Erro ao carregar dashboard', 'error');
  } finally {
    showLoading(false);
  }
}

/* ================= AUTH ================= */

async function checkAuth() {
  try {
    const res = await api.getCurrentUser();
    return res.success ? res.user : null;
  } catch {
    return null;
  }
}

/* ================= PAYMENT ================= */

async function loadPaymentStatus() {
  const res = await api.getPaymentStatus();
  paymentStatus = res.status;

  document.getElementById('quotaUnitValue').textContent =
    `R$ ${res.quotaValue.toFixed(2).replace('.', ',')}`;

  updateTotalAmount();

  if (paymentStatus === 'not_joined') {
    showPaymentSection('join');
  } else if (paymentStatus === 'pending') {
    showPaymentSection('pending');
  } else if (paymentStatus === 'claimed') {
    showWaitingSection();
  } else if (paymentStatus === 'confirmed') {
    document.getElementById('paymentSection').style.display = 'none';
    document.getElementById('waitingSection').style.display = 'none';
    document.getElementById('selectionSection').style.display = 'block';
  }
}

function showPaymentSection(state) {
  document.getElementById('paymentSection').style.display = 'block';
  document.getElementById('waitingSection').style.display = 'none';

  document.getElementById('joinBolaoBtn').style.display =
    state === 'join' ? 'inline-block' : 'none';

  document.getElementById('alreadyPaidBtn').style.display =
    state === 'pending' ? 'inline-block' : 'none';

  document.getElementById('paymentStatus').innerHTML =
    state === 'pending'
      ? '<p>⏳ Após pagar, clique em "Já paguei"</p>'
      : '';
}

function showWaitingSection() {
  document.getElementById('paymentSection').style.display = 'none';
  document.getElementById('waitingSection').style.display = 'block';
}

/* ================= ACTIONS ================= */

async function handleJoinBolao() {
  try {
    showLoading(true);
    const qty = parseInt(document.getElementById('quotaQuantity').value) || 1;
    await api.joinBolao(qty);
    showToast('Agora realize o pagamento via PIX', 'success');
    await loadPaymentStatus();
  } finally {
    showLoading(false);
  }
}

async function handleAlreadyPaid() {
  try {
    showLoading(true);
    await api.claimPaid();
    showToast('Pagamento registrado!', 'success');
    await loadPaymentStatus();
  } finally {
    showLoading(false);
  }
}

async function handleLogout() {
  await api.logout();
  window.location.href = '/';
}

/* ================= UTILS ================= */

function updateTotalAmount() {
  const qty = parseInt(document.getElementById('quotaQuantity').value) || 1;
  const unit = 10;
  document.getElementById('totalAmount').textContent =
    (qty * unit).toFixed(2).replace('.', ',');
}

async function loadBolaoInfo() {
  try {
    await api.getBolaoInfo();
  } catch {}
}

async function refreshData() {
  await loadPaymentStatus();
}

function showLoading(show) {
  document.getElementById('loadingOverlay').style.display = show ? 'flex' : 'none';
}

function showToast(msg, type = 'info') {
  const toast = document.getElementById('toast');
  toast.textContent = msg;
  toast.className = `toast toast-${type}`;
  toast.style.display = 'block';
  setTimeout(() => (toast.style.display = 'none'), 3000);
}

window.addEventListener('beforeunload', () => {
  if (refreshInterval) clearInterval(refreshInterval);
});
